# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

r_github_packages:
  - chuvanan/metrics

r_packages:
  - covr

after_success:
  - Rscript -e "covr::codecov()"
