# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auc_ <- function(actual, predicted) {
    .Call(`_metrics_auc_`, actual, predicted)
}

clip_ <- function(x, mi, ma) {
    .Call(`_metrics_clip_`, x, mi, ma)
}

confusion_matrix_ <- function(actual, predicted, cutoff) {
    .Call(`_metrics_confusion_matrix_`, actual, predicted, cutoff)
}

true_positive_rate_ <- function(actual, predicted, cutoff) {
    .Call(`_metrics_true_positive_rate_`, actual, predicted, cutoff)
}

true_negative_rate_ <- function(actual, predicted, cutoff) {
    .Call(`_metrics_true_negative_rate_`, actual, predicted, cutoff)
}

false_positive_rate_ <- function(actual, predicted, cutoff) {
    .Call(`_metrics_false_positive_rate_`, actual, predicted, cutoff)
}

